CREATE TABLE DOCTORS (
    DOCTOR_ID NUMBER,
    DOCTOR_NAME VARCHAR2(100),
    SPECIALIZATION VARCHAR2(100)
);

CREATE TABLE PATIENTS (
    PATIENT_ID NUMBER,
    PATIENT_NAME VARCHAR2(100),
    GENDER VARCHAR2(10)
);

CREATE TABLE APPOINTMENTS (
    APPOINTMENT_ID NUMBER,
    PATIENT_ID NUMBER,
    DOCTOR_ID NUMBER,
    APPOINTMENT_DATE DATE,
    CONSULTATION_FEE NUMBER
);

ALTER TABLE PATIENTS
ADD CONSTRAINT PK_PATIENTS PRIMARY KEY (PATIENT_ID);

ALTER TABLE DOCTORS
ADD CONSTRAINT PK_DOCTORS PRIMARY KEY (DOCTOR_ID);

ALTER TABLE APPOINTMENTS
ADD CONSTRAINT PK_APPOINTMENTS PRIMARY KEY (APPOINTMENT_ID);

ALTER TABLE APPOINTMENTS
ADD CONSTRAINT FK_PATIENT
FOREIGN KEY (PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID);

ALTER TABLE APPOINTMENTS
ADD CONSTRAINT FK_DOCTOR
FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORS(DOCTOR_ID);
